### ISSUE TITLE
VALUES not returned properly

### ISSUE THREAD

**Issue by korodit** [rigetticomputing/alexa#4]
I have been using alexa together with cl-yacc for a compiler I've been writing. Yacc requires the lexer to return the token type and its value in the form of (VALUES *token-type* *token-value*). Thus, in my implementation, the alexa defined lexer emitted values in the form above. Since the last update, alexa fails to return the token value and only the token type is emitted, resulting in the compiler failing to do its job. As a workaround, I set the alexa generated lexer to emit cons cells with the token type and the token value, and a wrapper closure of it is given to the parser, which takes the cons cell and emits it in the VALUES form. All worked without needing this workaround until the last update. Just letting you know, in case it is a bug which you did not know of, and because yacc is mentioned as an example in your README file.

**Comment by stylewarning** [comment]
@orestarod Somehow I missed this. Thanks for reporting!
